version: '3'
services:
  api:
    image: youtip/api:v1
    ports:
      - "8080:8080"
    volumes:
      - db-data:/usr/src/api/data
    networks:
      - youtip_demo_net

  nginx:
    image: youtip/nginx:v1
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - youtip_demo_net

networks:
  youtip_demo_net:

volumes:
  db-data: